### ISSUE TITLE
Add support for reading header packets spanning multiple pages

### ISSUE THREAD

**Issue by halcyonseeker** [fmang/opustags#59] opened 2023-01-02 20:37 UTC
Hi,

I'm trying to use opustags (built just now from the master branch) to embed lyrics in my music collection, but I keep running into this error message no matter which command-line options I pass:

```
error: Reading header packets spanning multiple pages are not yet supported. Please file an issue to make your wish known.
```

The file that's causing this issue was downloaded from YouTube with:

```sh
yt-dlp --extract-audio --audio-format opus --audio-quality 0 --embed-metadata --embed-thumbnail --sponsorblock-mark all --output '%(artist)s - %(track)s.%(ext)s' 'https://youtube.com/watch?v=xgIU9e1W0uU'
```

**Comment by zvezdochiot** [comment] 2023-01-02 21:36
Hi @halcyonseeker .

```shell
youtube-dl --extract-audio --audio-format opus --audio-quality 0 --add-metadata --embed-thumbnail --output '%(artist)s - %(track)s.%(ext)s' 'https://youtube.com/watch?v=xgIU9e1W0uU'
```

[opuscomment](https://github.com/Sound-Linux-More/opuscomment):
```shell
opuscomment SKÁLD\ -\ Gleipnir.opus 
language=und
handler_name=ISO Media file produced by Google Inc.
encoder=Lavc58.91.100 libopus
major_brand=isom
minor_version=512
compatible_brands=isomiso2mp41
title=Gleipnir
date=20180712
DESCRIPTION=Provided to YouTube by Universal Music Group

        Gleipnir · SKÁLD

        SKÁLD

        ℗ 2018 Decca Records France

        Released on: 2018-07-20

        Producer, Studio  Personnel, Recording  Engineer, Associated  Performer, Percussion, Interprète  Instrumental, Keyboards, Programming: Christophe Voisin-Boisvinet
        Producer, Executive  Producer: Edouard Brane
        Studio  Personnel, Recording  Engineer, Mixer: Adrien Thore
        Studio  Personnel, Mastering  Engineer: Alexis Bardinet
        Associated  Performer, Vocals, Interprète  Instrumental: Pierrick Valence
        Associated  Performer, Vocals: Xavier Bertrand
        Associated  Performer, Vocals: Mathieu Haussy
        Associated  Performer, Vocals: Justine Galmiche
        Associated  Performer, Percussion: Nicolas Montazaud
        Associated  Performer, Interprète  Instrumental: Jaufré Darroux
        Associated  Performer, Flute: Maxence des Oiseaux
        Author: Traditionnel
        Composer: Christophe Voisin-Boisvinet

        Auto-generated by YouTube.
purl=https://www.youtube.com/watch?v=xgIU9e1W0uU
artist=SKÁLD
album=SKÁLD

```

[libopustags](https://github.com/Sound-Linux-More/libopustags):
```shell
LD_LIBRARY_PATH=. ./opustags SKÁLD\ -\ Gleipnir.opus 
language=und
handler_name=ISO Media file produced by Google Inc.
encoder=Lavc58.91.100 libopus
major_brand=isom
minor_version=512
compatible_brands=isomiso2mp41
title=Gleipnir
date=20180712
DESCRIPTION=Provided to YouTube by Universal Music Group

Gleipnir · SKÁLD

SKÁLD

℗ 2018 Decca Records France

Released on: 2018-07-20

Producer, Studio  Personnel, Recording  Engineer, Associated  Performer, Percussion, Interprète  Instrumental, Keyboards, Programming: Christophe Voisin-Boisvinet
Producer, Executive  Producer: Edouard Brane
Studio  Personnel, Recording  Engineer, Mixer: Adrien Thore
Studio  Personnel, Mastering  Engineer: Alexis Bardinet
Associated  Performer, Vocals, Interprète  Instrumental: Pierrick Valence
Associated  Performer, Vocals: Xavier Bertrand
Associated  Performer, Vocals: Mathieu Haussy
Associated  Performer, Vocals: Justine Galmiche
Associated  Performer, Percussion: Nicolas Montazaud
Associated  Performer, Interprète  Instrumental: Jaufré Darroux
Associated  Performer, Flute: Maxence des Oiseaux
Author: Traditionnel
Composer: Christophe Voisin-Boisvinet

Auto-generated by YouTube.
purl=https://www.youtube.com/watch?v=xgIU9e1W0uU
artist=SKÁLD
album=SKÁLD

```

Good luck.

**Comment by halcyonseeker** [comment] 2023-01-03 01:23
Thank you, I was able to get it to work with opuscomment.  Further investigation revealed that opustags only yielded that error when the file had embedded cover art.

**Comment by zvezdochiot** [comment] 2023-01-03 08:14
@halcyonseeker say:
>Further investigation revealed that opustags only yielded that error when the file had embedded cover art.

This only applies to opustags (this), not [libopustags](https://github.com/Sound-Linux-More/libopustags).

**Comment by fmang** [comment] 2023-01-03 10:05
Duplicate of #49.

A cover art included in the comments can indeed easily cause a multi-page OpusTags header.

**Closed by fmang** 2023-01-03 10:05 UTC
